Update Mock OpenAI Client
protagolabs/Netmind-AI-XYZ pull request #6
Opened 2024-04-26 21:09 UTC by LANNDS18

## Description

 add mock class to simulate openai client behaviour, update test client to enable the argument checking

## Types of Changes

- [x] New feature (non-breaking change that adds functionality)

## Checklist

- [x] I have read the project's contributing guidelines.
- [x] My code follows the project's coding style.
- [x] I have written or updated unit tests for the new functionality.
- [x] I have updated the comments in code which is necessary,
- [x] I have rebased all the commit in my git.
- [x] I have updated the documentation as necessary.
- [x] I have added a descriptive commit message with a summary of the changes.

2024-04-30 06:53 UTC, BinLiang2021 commented
1. Line 48: The import statement should start from the root directory, like this: from xyz.utils.test_tool.mock_openai import MockOpenAI.
2. The comments and docstrings in test_client.py (e.g., lines 55, 79, 2-32) seem unchanged. Could you double-check to ensure they are updated appropriately?
3. There are some commented-out lines from 137 to 140. Is there a reason these lines haven't been deleted? If they are no longer needed, it might be cleaner to remove them.
4. The content after line 405 should not be in this file. Please move the unit tests to the test/xyz folder to maintain consistent directory structure with the xyz folder.
5. There appears to be an issue with the initialization requiring a logit_bias\n parameter. Why is this parameter mandatory? The absence of logit_bias leads to an error, which suggests that the default handling might need improvement.
6. There is currently no validation for an illegal model name during initialization, which does not trigger an error (other parameters being the same). I recommend adding a check both at initialization and during the request phase. Additionally, an illegal model name does not trigger an error during generation, which should be addressed to prevent runtime issues.

2024-04-30 06:56 UTC, BinLiang2021 requested changes

2024-04-30 06:56 UTC, BinLiang2021 commented on xyz/utils/test_tool/test_client.py
> +from mock_openai import MockOpenAI
Should be from xyz.utils.test_tool.mock_openai import MockOpenAI

2024-04-30 06:56 UTC, BinLiang2021 commented on xyz/utils/test_tool/test_client.py
> +    test_client = TestClient(api_key="sk-1", top_p=0.8911, n=2, logit_bias={"s": 0})
If I do not set n/logit_bias in the init method, it will raise error, why?

2024-04-30 15:29 UTC, LANNDS18 commented on xyz/utils/test_tool/test_client.py
> +    test_client = TestClient(api_key="sk-1", top_p=0.8911, n=2, logit_bias={"s": 0})
Bug-fix has been pushed

2024-04-30 15:30 UTC, LANNDS18 commented
Bug-fix has been pushed

2024-05-07 06:00 UTC, BinLiang2021 commented
1. Line 48: The import statement should start from the root directory, like this: from xyz.utils.test_tool.mock_openai import MockOpenAI. You did not fix this one.
2. why model name 'gpt-4-turbo' will raise an error?
3. In test_client.py line: 504. You did not import the time.

Could you please double check these error? And do the same check on the similar things.

2024-05-09 06:30 UTC, merged